server:
  port: 9002
  
 #jsp
spring:
  devtools:
    livereload:
      enabled: true
 
 #mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bunddeuk?createDatabaseIfNotExist=true
    username: root
    password: haemin1964
    driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis:
  type-aliases-package: data.*
  mapper-locations:
  - /mappers/**/*.xml

#file:
#  upload:
#    image: '/home/ec2-user/backup/thumbnail_image'
    